name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          flake8 --max-line-length=100 --exclude=__pycache__,logs .
      - name: Type check with mypy
        run: |
          mypy --ignore-missing-imports .
      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Enforce 80% coverage
        run: |
          python - <<'PY'
import sys
import xml.etree.ElementTree as ET
root = ET.parse('coverage.xml').getroot()
total = root.find('coverage').attrib['line-rate']
coverage = float(total) * 100
print(f"coverage: {coverage:.2f}%")
if coverage < 80:
    sys.exit(1)
PY
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
